"""Small, deterministic food catalogue for immediate recommendation screening.

Values are representative nutrient amounts per 100 g. They are used only to
screen and simulate recommendations; when a user actually logs a suggestion,
Quinone still resolves the selected food through the normal USDA workflow.
"""

from __future__ import annotations

from typing import Any


FOOD_RECOMMENDATION_CATALOG: tuple[dict[str, Any], ...] = (
    {
        "id": "plain_low_fat_yogurt",
        "name": "Plain low-fat yogurt",
        "search_query": "yogurt plain low fat",
        "serving_g": 170.0,
        "meal_roles": ["breakfast", "snack", "side"],
        "diet_tags": ["vegetarian", "gluten_free"],
        "allergens": ["milk", "dairy"],
        "nutrients": {
            "energy_kcal": 63, "protein_g": 5.3, "fat_g": 1.6,
            "saturated_fat_g": 1.0, "carbohydrate_g": 7.0,
            "sugars_g": 7.0, "fiber_g": 0.0, "calcium_mg": 183,
            "phosphorus_mg": 144, "potassium_mg": 234,
            "sodium_mg": 70, "vitamin_b12_ug": 0.56,
        },
    },
    {
        "id": "lentils_cooked",
        "name": "Cooked lentils",
        "search_query": "lentils mature seeds cooked boiled without salt",
        "serving_g": 150.0,
        "meal_roles": ["lunch", "dinner", "side"],
        "diet_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "nutrients": {
            "energy_kcal": 116, "protein_g": 9.0, "fat_g": 0.4,
            "saturated_fat_g": 0.05, "carbohydrate_g": 20.1,
            "fiber_g": 7.9, "sugars_g": 1.8, "iron_mg": 3.3,
            "folate_ug": 181, "magnesium_mg": 36, "potassium_mg": 369,
            "sodium_mg": 2, "zinc_mg": 1.3,
        },
    },
    {
        "id": "chickpeas_cooked",
        "name": "Cooked chickpeas",
        "search_query": "chickpeas cooked boiled without salt",
        "serving_g": 130.0,
        "meal_roles": ["lunch", "dinner", "snack", "side"],
        "diet_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "nutrients": {
            "energy_kcal": 164, "protein_g": 8.9, "fat_g": 2.6,
            "saturated_fat_g": 0.27, "carbohydrate_g": 27.4,
            "fiber_g": 7.6, "sugars_g": 4.8, "iron_mg": 2.9,
            "folate_ug": 172, "magnesium_mg": 48, "potassium_mg": 291,
            "sodium_mg": 7, "zinc_mg": 1.5,
        },
    },
    {
        "id": "tofu_calcium_set",
        "name": "Calcium-set firm tofu",
        "search_query": "tofu firm prepared with calcium",
        "serving_g": 120.0,
        "meal_roles": ["lunch", "dinner"],
        "diet_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": ["soy"],
        "nutrients": {
            "energy_kcal": 144, "protein_g": 17.3, "fat_g": 8.7,
            "saturated_fat_g": 1.3, "carbohydrate_g": 2.8,
            "fiber_g": 2.3, "calcium_mg": 683, "iron_mg": 2.7,
            "magnesium_mg": 58, "potassium_mg": 237, "sodium_mg": 14,
        },
    },
    {
        "id": "egg_boiled",
        "name": "Boiled egg",
        "search_query": "egg whole cooked hard boiled",
        "serving_g": 50.0,
        "meal_roles": ["breakfast", "snack", "lunch"],
        "diet_tags": ["vegetarian", "gluten_free"],
        "allergens": ["egg"],
        "nutrients": {
            "energy_kcal": 155, "protein_g": 12.6, "fat_g": 10.6,
            "saturated_fat_g": 3.3, "carbohydrate_g": 1.1,
            "cholesterol_mg": 373, "sodium_mg": 124,
            "vitamin_b12_ug": 1.1, "selenium_ug": 30.8,
        },
    },
    {
        "id": "chicken_breast_roasted",
        "name": "Roasted chicken breast",
        "search_query": "chicken breast meat only cooked roasted",
        "serving_g": 120.0,
        "meal_roles": ["lunch", "dinner"],
        "diet_tags": ["gluten_free"],
        "allergens": [],
        "nutrients": {
            "energy_kcal": 165, "protein_g": 31.0, "fat_g": 3.6,
            "saturated_fat_g": 1.0, "carbohydrate_g": 0.0,
            "sodium_mg": 74, "potassium_mg": 256, "selenium_ug": 27.6,
            "vitamin_b6_mg": 0.6,
        },
    },
    {
        "id": "salmon_cooked",
        "name": "Cooked salmon",
        "search_query": "salmon cooked dry heat",
        "serving_g": 100.0,
        "meal_roles": ["lunch", "dinner"],
        "diet_tags": ["pescatarian", "gluten_free"],
        "allergens": ["fish"],
        "nutrients": {
            "energy_kcal": 206, "protein_g": 22.1, "fat_g": 12.4,
            "saturated_fat_g": 3.1, "carbohydrate_g": 0.0,
            "omega3_g": 2.3, "vitamin_d_ug": 13.0,
            "vitamin_b12_ug": 3.2, "selenium_ug": 41.4,
            "potassium_mg": 384, "sodium_mg": 59,
        },
    },
    {
        "id": "rolled_oats_cooked",
        "name": "Cooked rolled oats",
        "search_query": "oats regular quick cooked with water without salt",
        "serving_g": 180.0,
        "meal_roles": ["breakfast", "snack"],
        "diet_tags": ["vegan", "vegetarian"],
        "allergens": ["gluten"],
        "nutrients": {
            "energy_kcal": 71, "protein_g": 2.5, "fat_g": 1.5,
            "saturated_fat_g": 0.3, "carbohydrate_g": 12.0,
            "fiber_g": 1.7, "sugars_g": 0.3, "iron_mg": 0.9,
            "magnesium_mg": 27, "phosphorus_mg": 77, "sodium_mg": 2,
        },
    },
    {
        "id": "chia_seeds",
        "name": "Chia seeds",
        "search_query": "seeds chia dried",
        "serving_g": 20.0,
        "meal_roles": ["breakfast", "snack", "topping"],
        "diet_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "nutrients": {
            "energy_kcal": 486, "protein_g": 16.5, "fat_g": 30.7,
            "saturated_fat_g": 3.3, "carbohydrate_g": 42.1,
            "fiber_g": 34.4, "omega3_g": 17.8, "calcium_mg": 631,
            "iron_mg": 7.7, "magnesium_mg": 335, "sodium_mg": 16,
        },
    },
    {
        "id": "almonds_unsalted",
        "name": "Unsalted almonds",
        "search_query": "almonds raw",
        "serving_g": 25.0,
        "meal_roles": ["snack", "topping"],
        "diet_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": ["tree_nuts", "almond"],
        "nutrients": {
            "energy_kcal": 579, "protein_g": 21.2, "fat_g": 49.9,
            "saturated_fat_g": 3.8, "carbohydrate_g": 21.6,
            "fiber_g": 12.5, "calcium_mg": 269, "iron_mg": 3.7,
            "magnesium_mg": 270, "potassium_mg": 733, "sodium_mg": 1,
            "vitamin_e_mg": 25.6,
        },
    },
    {
        "id": "blueberries_raw",
        "name": "Blueberries",
        "search_query": "blueberries raw",
        "serving_g": 100.0,
        "meal_roles": ["breakfast", "snack", "dessert", "topping"],
        "diet_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "nutrients": {
            "energy_kcal": 57, "protein_g": 0.7, "fat_g": 0.3,
            "carbohydrate_g": 14.5, "fiber_g": 2.4, "sugars_g": 10.0,
            "vitamin_c_mg": 9.7, "vitamin_k_ug": 19.3,
            "potassium_mg": 77, "sodium_mg": 1,
        },
    },
    {
        "id": "orange_raw",
        "name": "Orange",
        "search_query": "oranges raw all commercial varieties",
        "serving_g": 130.0,
        "meal_roles": ["breakfast", "snack", "dessert"],
        "diet_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "nutrients": {
            "energy_kcal": 47, "protein_g": 0.9, "fat_g": 0.1,
            "carbohydrate_g": 11.8, "fiber_g": 2.4, "sugars_g": 9.4,
            "vitamin_c_mg": 53.2, "folate_ug": 30,
            "potassium_mg": 181, "calcium_mg": 40, "sodium_mg": 0,
        },
    },
    {
        "id": "spinach_cooked",
        "name": "Cooked spinach",
        "search_query": "spinach cooked boiled drained without salt",
        "serving_g": 100.0,
        "meal_roles": ["lunch", "dinner", "side"],
        "diet_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "nutrients": {
            "energy_kcal": 23, "protein_g": 3.0, "fat_g": 0.3,
            "carbohydrate_g": 3.8, "fiber_g": 2.4, "calcium_mg": 136,
            "iron_mg": 3.6, "magnesium_mg": 87, "potassium_mg": 466,
            "folate_ug": 146, "vitamin_c_mg": 9.8,
            "vitamin_k_ug": 493, "sodium_mg": 70,
        },
    },
    {
        "id": "broccoli_cooked",
        "name": "Steamed broccoli",
        "search_query": "broccoli cooked steamed without salt",
        "serving_g": 120.0,
        "meal_roles": ["lunch", "dinner", "side"],
        "diet_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "nutrients": {
            "energy_kcal": 35, "protein_g": 2.4, "fat_g": 0.4,
            "carbohydrate_g": 7.2, "fiber_g": 3.3, "sugars_g": 1.4,
            "vitamin_c_mg": 64.9, "vitamin_k_ug": 141,
            "folate_ug": 108, "calcium_mg": 40, "potassium_mg": 293,
            "sodium_mg": 41,
        },
    },
    {
        "id": "sweet_potato_baked",
        "name": "Baked sweet potato",
        "search_query": "sweet potato cooked baked in skin flesh without salt",
        "serving_g": 150.0,
        "meal_roles": ["lunch", "dinner", "snack", "side"],
        "diet_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "nutrients": {
            "energy_kcal": 90, "protein_g": 2.0, "fat_g": 0.2,
            "carbohydrate_g": 20.7, "fiber_g": 3.3, "sugars_g": 6.5,
            "vitamin_a_ug": 961, "vitamin_c_mg": 19.6,
            "potassium_mg": 475, "magnesium_mg": 27, "sodium_mg": 36,
        },
    },
    {
        "id": "avocado_raw",
        "name": "Avocado",
        "search_query": "avocados raw all commercial varieties",
        "serving_g": 70.0,
        "meal_roles": ["breakfast", "lunch", "snack", "side"],
        "diet_tags": ["vegan", "vegetarian", "gluten_free"],
        "allergens": [],
        "nutrients": {
            "energy_kcal": 160, "protein_g": 2.0, "fat_g": 14.7,
            "saturated_fat_g": 2.1, "monounsaturated_fat_g": 9.8,
            "carbohydrate_g": 8.5, "fiber_g": 6.7, "sugars_g": 0.7,
            "potassium_mg": 485, "folate_ug": 81, "sodium_mg": 7,
        },
    },
)

